Repository BourbonWarfare/POTATO, pull requests merged in 2018-02, with the labels that each got.

#213 Move to cba settings, refactor UI
  addons/missionModules/ACE_Settings.hpp
  addons/missionModules/CfgVehicles.hpp
  addons/missionModules/Displays.hpp
  addons/missionModules/UI_RscAttributes.hpp
  addons/missionModules/XEH_PREP.hpp
  addons/missionModules/XEH_postInit.sqf
  addons/missionModules/XEH_preInit.sqf
  addons/missionModules/config.cpp
  addons/missionModules/functions/fnc_manInitEH.sqf
  addons/missionModules/functions/fnc_setSkillsDialogLoad.sqf
  addons/missionModules/functions/fnc_setSkillsDialogSet.sqf
  addons/missionModules/functions/fnc_setSkillsDialogSliderChange.sqf
  addons/missionModules/functions/fnc_setSkillsLocal.sqf
  addons/missionModules/functions/fnc_setSkillsModule.sqf
  addons/missionModules/functions/fnc_sideMarker.sqf
  addons/missionModules/functions/fnc_zeusAttributes.sqf
  addons/missionModules/functions/fnc_zeusAttributes_globalSetSkill.sqf
  addons/missionModules/functions/fnc_zeusAttributes_missionHint.sqf
  addons/missionModules/functions/fnc_zeus_banziCharge.sqf
  addons/missionModules/functions/fnc_zeus_globalSetSkill.sqf
  addons/missionModules/functions/fnc_zeus_missionHint.sqf
  addons/missionModules/functions/script_component.hpp
  addons/missionModules/initSettings.sqf
  addons/missionModules/script_component.hpp
Labels: Cleanup, enhancement

#216 Remove ACE settings from Potato Radio
  addons/radios/ACE_Settings.hpp
  addons/radios/XEH_postInit.sqf
  addons/radios/config.cpp
  addons/radios/functions/fnc_acreGlobalSetControlsFromGVars.sqf
  addons/radios/functions/fnc_acreGlobalSetGVarsFromString.sqf
  addons/radios/functions/fnc_acreSideControlChannelEditChange.sqf
  addons/radios/functions/fnc_acreSideControlRadioChange.sqf
  addons/radios/functions/fnc_acreSideControlSideChange.sqf
  addons/radios/functions/fnc_acreSideSetControlsFromGVars.sqf
  addons/radios/functions/fnc_acreSideSetGVarsFromString.sqf
  addons/radios/functions/fnc_addAcreBriefing.sqf
  addons/radios/functions/fnc_addSharedChannel.sqf
  addons/radios/functions/fnc_babelAttributeLoad.sqf
  addons/radios/functions/fnc_babelAttributeSave.sqf
  addons/radios/functions/fnc_babelControlLoad.sqf
  addons/radios/functions/fnc_channelAttributeLoad.sqf
  addons/radios/functions/fnc_channelControlLoad.sqf
  addons/radios/functions/fnc_fillChannelArray.sqf
  addons/radios/functions/fnc_initializeRadios.sqf
  addons/radios/functions/fnc_setChannel.sqf
  addons/radios/functions/fnc_setChannelArrays.sqf
  addons/radios/functions/fnc_setChannels.sqf
  addons/radios/functions/fnc_setupPlayer.sqf
  addons/radios/script_component.hpp
Labels: Bug Fix, enhancement, needs testing

#214 Fix Burst-Value Oversight on CUP MG36, CUP XM8, and RHS M27 IAR
  addons/aiCfgFixes/CfgWeapons.hpp
  addons/aiCfgFixes/XEH_PREP.hpp
  addons/aiCfgFixes/functions/fnc_ensurePlayerBurst.sqf
  addons/aiCfgFixes/functions/fnc_generateWeapons.sqf
Labels: Bug Fix

#217 Remove RGMuzzle from M70s
  addons/miscFixes/CfgWeapons.hpp
Labels: enhancement

#220 Settings cleanup
  addons/adminComs/script_component.hpp
  addons/adminMenu/script_component.hpp
  addons/aiCfgFixes/script_component.hpp
  addons/assignGear/script_component.hpp
  addons/briefing/script_component.hpp
  addons/core/XEH_preInit.sqf
  addons/core/initSettings.sqf
  addons/core/script_component.hpp
  addons/filledSmoke/script_component.hpp
  addons/flares/script_component.hpp
  addons/fortify/script_component.hpp
  addons/markers/script_component.hpp
  addons/massCompat/script_component.hpp
  addons/memes/script_component.hpp
  addons/miscFixes/script_component.hpp
  addons/missionModules/script_component.hpp
  addons/radios/script_component.hpp
  addons/ratios/script_component.hpp
  addons/recruits/script_component.hpp
  addons/reinforceToHC/script_component.hpp
  addons/respawn/script_component.hpp
  addons/safeStart/XEH_preInit.sqf
  addons/safeStart/initSettings.sqf
  addons/safeStart/script_component.hpp
  addons/serverMonitor/script_component.hpp
  addons/setVehicleAmmo/script_component.hpp
  addons/settings/script_component.hpp
  addons/spectate/script_component.hpp
  addons/teamColors/script_component.hpp
  addons/units/script_component.hpp
  addons/vz99/script_component.hpp
  addons/zeusFactory/script_component.hpp
  addons/zeusHC/XEH_preInit.sqf
  addons/zeusHC/initSettings.sqf
  addons/zeusHC/script_component.hpp
  addons/zeusMonitor/script_component.hpp
  addons/zeusRecon/script_component.hpp
Labels: Cleanup
