Repository BourbonWarfare/POTATO, pull requests merged in 2024-11, with the labels that each got.

#586 Adds JSRS Compat for NH90
  addons/miscFixes/patchHAFMHelis/config.cpp
Labels: enhancement

#585 massCompat - Add custom HV 40x53mm HE and HEDP grenades
  addons/massCompat/CfgAmmo.hpp
  addons/massCompat/CfgMagazineWells.hpp
  addons/massCompat/CfgMagazines.hpp
  addons/massCompat/CfgWeapons.hpp
  addons/massCompat/script_component.hpp
  addons/miscFixes/patchCUP/config.cpp
  addons/setVehicleAmmo/functions/fnc_attributeLoad.sqf
Labels: enhancement

#584 Miscelaneous Fixes and Edits Based on Feedback from the 1.3.47 Potato Update
  addons/aceEdits/README.md
  addons/aceEdits/config.cpp
  addons/armor_modifier_ace/functions/fnc_setClassArmor.sqf
  addons/armor_modifier_ace/functions/fnc_setUnitArmor.sqf
  addons/miscMedical/XEH_postInit.sqf
  addons/missionTesting/XEH_postInit.sqf
  addons/safeStart/functions/fnc_initForceEndSafeStart.sqf
Labels: Bug Fix, Cleanup

#590 Adds a faux KAC LAMG
  addons/customGear/CfgWeapons.hpp
  addons/customGear/config.hpp
  addons/customGear/fauxC7/CfgWeapons.hpp
  addons/customGear/fauxC7/config.cpp
  addons/customGear/fauxLAMG/CfgWeapons.hpp
  addons/customGear/fauxLAMG/config.cpp
Labels: enhancement

#603 Kimi's HMD 20mm Cannon Fix
  addons/miscFixes/patchHMD/config.cpp
Labels: Bug Fix

#583 Adds a low-count painkiller alternative
  addons/miscMedical/ACE_Medical_Treatment.hpp
  addons/miscMedical/ACE_Medical_Treatment_Actions.hpp
  addons/miscMedical/CfgMagazines.hpp
  addons/miscMedical/CfgVehicles.hpp
  addons/miscMedical/CfgWeapons.hpp
  addons/miscMedical/Naloxone_Patch.hpp
  addons/miscMedical/config.cpp
  addons/miscMedical/ui/pkblister_ca.paa
Labels: enhancement, help wanted
